version: "3.6"
services:
  wordpress:
    image: wordpress:latest
    container_name: wordpress
    volumes:
      - ./volumes/www:/var/www/html/wp-content
    environment:
      - WORDPRESS_DB_NAME=travel_db
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=root
      - WORDPRESS_DB_PASSWORD=PWD
    depends_on:
      - db
      - phpmyadmin
    restart: always
    ports:
      - 80:80

  db:
    image: mariadb:latest
    container_name: db
    volumes:
      - ./volumes/data:/var/lib/mysql
      # - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      - MYSQL_ROOT_PASSWORD=Kissaivlis!
      - MYSQL_USER=root
      - MYSQL_PASSWORD=PWD
      - MYSQL_DATABASE=travel_db
    restart: always

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - 8180:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: PWD
