version: "3.6"
services:

  portainer:
    container_name: www_portainer
    restart: unless-stopped
    image: portainer/portainer-ce:latest
    # ports:
        #- "8100:8000"
        #- "7436:9000"
        # - "7436:9443"      
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./docker/portainer:/data

  ftpd:
    container_name: www_ftpd
    restart: unless-stopped
    image: stilliard/pure-ftpd
    ports:
        - "9021:21"
        - "30000-30009:30000-30009"
    environment:
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: ${DB_PASS}
      FTP_USER_HOME: /www
      PUBLICHOST: localhost
    volumes:
      - ./volumes/www/:/www
          
  nginx:
    image: nginx:stable
    restart: unless-stopped
    container_name: www_nginx
    volumes:
      - ./volumes/www/:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available/:/etc/nginx/sites-available
    #tty: true
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: "json-file"
      options:
          max-size: "11k"

  db:
    image: mariadb:10.6.5-focal
    restart: unless-stopped
    container_name: www_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
      TZ: Europe/Bucharest
    volumes:
      - ./volumes/db/:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: www_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      UPLOAD_LIMIT: 500M
      MAX_EXECUTION_TIME: 600
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
  
  www_travel:
    image: wordpress:latest
    restart: unless-stopped
    container_name: www_travel
    volumes:
      - ./volumes/www_travel:/var/www/html/wp-content
      - ./volumes/www_travel/php:/usr/local/etc/php
    environment:
      - WORDPRESS_DB_NAME=travel_db
      - WORDPRESS_TABLE_PREFIX=wp_
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=${DB_USER}
      - WORDPRESS_DB_PASSWORD=${DB_PASS}

